<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-09T16:53:43 IST" name="Suite" finished-at="2022-05-09T16:54:10 IST" duration-ms="26475">
    <groups>
    </groups>
    <test started-at="2022-05-09T16:53:43 IST" name="Test" finished-at="2022-05-09T16:54:10 IST" duration-ms="26475">
      <class name="testcases.LoginTest">
        <test-method is-config="true" signature="dataSetup()[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:53:43 IST" name="dataSetup" finished-at="2022-05-09T16:53:44 IST" duration-ms="692" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataSetup -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:53:44 IST" name="setUp" finished-at="2022-05-09T16:53:48 IST" duration-ms="4277" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.LoginTest.LoginFailureTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="LoginFailureTest()[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:53:48 IST" name="LoginFailureTest" finished-at="2022-05-09T16:53:56 IST" duration-ms="8022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailureTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:53:56 IST" name="tearDown" finished-at="2022-05-09T16:53:57 IST" duration-ms="82" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:53:57 IST" name="setUp" finished-at="2022-05-09T16:53:59 IST" duration-ms="2076" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.LoginTest.loginSuccessTest() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginSuccessTest()[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:53:59 IST" name="loginSuccessTest" finished-at="2022-05-09T16:54:06 IST" duration-ms="7482" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Learning on Simplilearn.] but found [Learning on Simplilearn]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Learning on Simplilearn.] but found [Learning on Simplilearn]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testcases.LoginTest.loginSuccessTest(LoginTest.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSuccessTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:54:09 IST" name="tearDown" finished-at="2022-05-09T16:54:10 IST" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="dataTearDown()[pri:0, instance:testcases.LoginTest@618425b5]" started-at="2022-05-09T16:54:10 IST" name="dataTearDown" finished-at="2022-05-09T16:54:10 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataTearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
